### ISSUE TITLE
兼容 dcat-admin2.0 请求

### ISSUE THREAD

**Issue by wskeee** [super-eggs/dcat-admin-extensions-distpicker#7]
dcat-admin目前已经更新到2.0版本，版本升级后无法适应使用，能不能发布兼容版本？

**Comment by super-eggs** [comment]
好的，我预计这两天来处理。

**Comment by hanjinye** [comment]
请问一下2.0兼容现在进展怎么样了？谢谢

**Comment by super-eggs** [comment]
> 请问一下2.0兼容现在进展怎么样了?谢谢

我更换了仓库，现在是这个 [super-eggs/dcat-distpicker](https://github.com/super-eggs/dcat-distpicker)，欢迎使用、反馈。

**Comment by hanjinye** [comment]
> > 请问一下2.0兼容现在进展怎么样了?谢谢
> 
> 我更换了仓库，现在是这个 [super-eggs/dcat-distpicker](https://github.com/super-eggs/dcat-distpicker)，欢迎使用、反馈。

十分感谢，辛苦了
